= Dispatch Notification Documentation

[cols="1,1,1,1,1,1,1,1", options="header"]
|===
|xmlElement |BMECAT |attribute |attributeValue |sampleValue |mustCanShould |dataType |description

|<?xml version="1.0" encoding="utf-8" standalone="yes"?>
| | | | |must | |Static

|DISPATCHNOTIFICATION
| |xmlns |http://www.opentrans.org/XMLSchema/2.1 | |must | |Static

|DISPATCHNOTIFICATION
| |version |2.1 | |must | |Static

|DISPATCHNOTIFICATION
|BMECAT |xmlns:bmecat |http://www.bmecat.org/bmecat/2005 | |must |string |namespace can be defined or directly in element

|• DISPATCHNOTIFICATION_HEADER
| | | | |must |element |

|• • DISPATCHNOTIFICATION_INFO
| | | | |must |element |

|• • • DISPATCHNOTIFICATION_ID
| | | |DN1122334455 |must |string |

|• • • DISPATCHNOTIFICATION_DATE
| | | |2024-06-28T00:00:00+01:00 |must |datetime |The format must be YYYY-MM-DDTHH:MM:SS+00:00

|• • • PARTIES
| | | | |must |element |

|• • • • PARTY
| | | | |must |element |

|• • • • • PARTY_ID
|BMECAT | | |7609999129308 |must |string |This value must be identical with the IDREF of the PARTY_ROLE

|• • • • • PARTY_ROLE
| | | |supplier |must |string |Must have exactly 1 supplier and 1 buyer

|• • • • • ADDRESS
| | | | |must |element |

|• • • • • • NAME
|BMECAT | | |BRACK.CH AG |must |string |Supplier Name

|• • DISPATCHNOTIFICATION_PARTIES_REFERENCE
| | | | |must |element |

|• • • BUYER_IDREF
|BMECAT |type |supplier_specific |7609999129308 |must |string |Must match buyer PARTY_ID

|• • • SUPPLIER_IDREF
|BMECAT |type |customer_specific |7990000000009 |must |string |Must match supplier PARTY_ID

|• DISPATCHNOTIFICATION_ITEM_LIST
| | | | |must |element |

|• • DISPATCHNOTIFICATION_ITEM
| | | | |must |element |

|• • • LINE_ITEM_ID
| | | |10000 |must |integer |

|• • • PRODUCT_ID
| | | | |must |element |

|• • • • SUPPLIER_PID
|BMECAT | | |73.83587 |must |string |Supplier SKU

|• • • QUANTITY
| | | |1 |must |integer |

|• • • ORDER_UNIT
|BMECAT | | |C62 |must |string |Must be C62

|• • • PRODUCT_PRICE_FIX
| | | | |must |element |

|• • • • PRICE_AMOUNT
|BMECAT | | |5.34 |must |decimal |

|• • • DELIVERY_DATE
| | | | |can |element |

|• • • • DELIVERY_START_DATE
| | | |2024-07-01 |must |date |

|• • • • DELIVERY_END_DATE
| | | |2024-07-01 |must |date |

|• DISPATCHNOTIFICATION_SUMMARY
| | | | |can |element |

|• • TOTAL_ITEM_NUM
| | | |70 |can |integer |Summary of DISPATCHNOTIFICATION_ITEM
|===

---

== XML Structure

* DISPATCHNOTIFICATION
** DISPATCHNOTIFICATION_HEADER
*** DISPATCHNOTIFICATION_INFO
**** DISPATCHNOTIFICATION_ID
**** DISPATCHNOTIFICATION_DATE
**** PARTIES
***** PARTY
****** PARTY_ID
****** PARTY_ROLE
****** ADDRESS
******* NAME
**** DISPATCHNOTIFICATION_PARTIES_REFERENCE
***** BUYER_IDREF
***** SUPPLIER_IDREF
** DISPATCHNOTIFICATION_ITEM_LIST
*** DISPATCHNOTIFICATION_ITEM
**** LINE_ITEM_ID
**** PRODUCT_ID
***** SUPPLIER_PID
**** QUANTITY
**** ORDER_UNIT
**** PRODUCT_PRICE_FIX
***** PRICE_AMOUNT
**** DELIVERY_DATE
***** DELIVERY_START_DATE
***** DELIVERY_END_DATE
** DISPATCHNOTIFICATION_SUMMARY
*** TOTAL_ITEM_NUM

== Sample File

[source,xml]
----
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<DISPATCHNOTIFICATION
    xmlns="http://www.opentrans.org/XMLSchema/2.1" version="2.1"
    xmlns:bmecat="http://www.bmecat.org/bmecat/2005">
    <DISPATCHNOTIFICATION_HEADER>
        <DISPATCHNOTIFICATION_INFO>
            <DISPATCHNOTIFICATION_ID>DN1122334455</DISPATCHNOTIFICATION_ID>
            <DISPATCHNOTIFICATION_DATE>2024-05-11T10:00:00+01:00</DISPATCHNOTIFICATION_DATE>
            <DELIVERY_DATE>
                <DELIVERY_START_DATE>2024-02-29T10:00:00+01:00</DELIVERY_START_DATE>
                <DELIVERY_END_DATE>2024-02-29T10:00:00+01:00</DELIVERY_END_DATE>
            </DELIVERY_DATE>
            <PARTIES>
                <PARTY>
                    <bmecat:PARTY_ID type="buyer_specific">L123456</bmecat:PARTY_ID>
                    <bmecat:PARTY_ID type="gln">760000000000</bmecat:PARTY_ID>
                    <PARTY_ROLE>supplier</PARTY_ROLE>
                </PARTY>
                <PARTY>
                    <bmecat:PARTY_ID type="buyer_specific">K22222</bmecat:PARTY_ID>
                    <PARTY_ROLE>final_delivery</PARTY_ROLE>
                    <ADDRESS>
                        <bmecat:NAME>Max Muster</bmecat:NAME>
                        <bmecat:STREET>Gartenweg 123</bmecat:STREET>
                        <bmecat:ZIP>1212</bmecat:ZIP>
                        <bmecat:CITY>Musterlingen</bmecat:CITY>
                    </ADDRESS>
                </PARTY>
                <PARTY>
                    <bmecat:PARTY_ID type="buyer_specific">A1234567</bmecat:PARTY_ID>
                    <bmecat:PARTY_ID type="gln">769999999999</bmecat:PARTY_ID>
                    <PARTY_ROLE>buyer</PARTY_ROLE>
                </PARTY>
            </PARTIES>
            <bmecat:SUPPLIER_IDREF type="buyer_specific">L123456</bmecat:SUPPLIER_IDREF>
            <bmecat:BUYER_IDREF type="buyer_specific">A1234567</bmecat:BUYER_IDREF>
            <SHIPMENT_PARTIES_REFERENCE>
                <DELIVERY_IDREF type="buyer_specific">K22222</DELIVERY_IDREF>
            </SHIPMENT_PARTIES_REFERENCE>
            <SHIPMENT_ID>SHIP_ID_1234567</SHIPMENT_ID>
            <TRACKING_TRACING_URL>www.sometrackingpage.com/trackandtrace/findMySendungsnummer</TRACKING_TRACING_URL>
        </DISPATCHNOTIFICATION_INFO>
    </DISPATCHNOTIFICATION_HEADER>
    <DISPATCHNOTIFICATION_ITEM_LIST>
        <DISPATCHNOTIFICATION_ITEM>
            <LINE_ITEM_ID>1</LINE_ITEM_ID>
            <PRODUCT_ID>
                <bmecat:BUYER_PID>1567285</bmecat:BUYER_PID>
                <bmecat:DESCRIPTION_SHORT>Notebooktasche</bmecat:DESCRIPTION_SHORT>
            </PRODUCT_ID>
            <QUANTITY>2</QUANTITY>
            <bmecat:ORDER_UNIT>C62</bmecat:ORDER_UNIT>
            <ORDER_REFERENCE>
                <ORDER_ID>1990845089</ORDER_ID>
                <LINE_ITEM_ID>300</LINE_ITEM_ID>
            </ORDER_REFERENCE>
            <SHIPMENT_PARTIES_REFERENCE>
                <DELIVERY_IDREF type="buyer_specific">K22222</DELIVERY_IDREF>
            </SHIPMENT_PARTIES_REFERENCE>
        </DISPATCHNOTIFICATION_ITEM>
        <DISPATCHNOTIFICATION_ITEM>
            <LINE_ITEM_ID>2</LINE_ITEM_ID>
            <PRODUCT_ID>
                <bmecat:BUYER_PID>1567326</bmecat:BUYER_PID>
                <bmecat:DESCRIPTION_SHORT>Some other product text, little longer</bmecat:DESCRIPTION_SHORT>
            </PRODUCT_ID>
            <QUANTITY>2</QUANTITY>
            <bmecat:ORDER_UNIT>C62</bmecat:ORDER_UNIT>
            <ORDER_REFERENCE>
                <ORDER_ID>1990845089</ORDER_ID>
                <LINE_ITEM_ID>13</LINE_ITEM_ID>
            </ORDER_REFERENCE>
            <SHIPMENT_PARTIES_REFERENCE>
                <DELIVERY_IDREF type="buyer_specific">K22222</DELIVERY_IDREF>
            </SHIPMENT_PARTIES_REFERENCE>
        </DISPATCHNOTIFICATION_ITEM>
    </DISPATCHNOTIFICATION_ITEM_LIST>
    <DISPATCHNOTIFICATION_SUMMARY>
        <TOTAL_ITEM_NUM>2</TOTAL_ITEM_NUM>
    </DISPATCHNOTIFICATION_SUMMARY>
</DISPATCHNOTIFICATION>
----
